### PR TITLE
Initial junior skeleton

### PR DESCRIPTION
**Pull request by fandasson**

### CODE REVIEW

**Comment by fandasson** [comment]
@petrdsvoboda A Kick-off; Any feedback welcome. Text of README.md is more draft, it may need some rephrasing. 

What is missing is an API server, but that should be easy. I'm going to copy the one Lukáš wrote for his assignment :-D

The code contains quite a few bugs. Intentionally.

**Comment by petrdsvoboda** [comment]
At the moment, just one note that I would add to the README for people on `node` 17+ and who don't use `nvm` (like me). 

When starting `storybook`, it crashes with `error:03000086:digital envelope routines::initialization error`. 
This setting of env variable enables to start it without the error - `export NODE_OPTIONS=--openssl-legacy-provider`.

**Comment by fandasson** [comment]
> At the moment, just one note that I would add to the README for people on `node` 17+ and who don't use `nvm` (like me).

Good catch. I set the node version to 16, but that will work only for users using `volta`.

**Review by petrdsvoboda — APPROVED** [review]
Looks good :)

**Pull request merged**
